# Generated by Django 5.0.7 on 2024-08-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kgllm", "0002_userinfo_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
